### ISSUE TITLE
Variant closer to vim's gruvbox theme

### ISSUE THREAD

**Issue by prokolyvakis** [jdinhify/vscode-theme-gruvbox#36]
First of all, thanks for your amazing work!

I would like to ask whether is possible to add a variant which is closer to the colour scheme of [vim's gruvbox theme](https://github.com/morhetz/gruvbox).

Thanks in advance!

**Comment by jdinhify** [comment]
Hi @prokolyvakis ,
Thanks for taking time to open this.

Could you please elaborate on the "closeness" to the vim colour scheme? Is this about the colour accuracy, or syntax highlighting, or anything else?

Maybe a bit of background - the starting intention of this theme was to match as much as I could from the original vim theme, but there were some factors that made it not possible (with my time and expertise), most important ones were:
- I was only using web development languages (HTML, CSS, JavaScript) at the time so the theme was created based on my reference & preferences on those languages, with the hope that it will evolve when there are more users (that I'm happy to receive contributions over the years ❤️)
- vim's syntax highlighting was (is?) different from vscode;  in fact, vscode highlighted a lot more stuff compared to vim. The difference were even wider with different vim plugins (e.g. `vim-javascript` vs `YAJS`). The same also applied for vscode, such as `babel` extension vs built-in javascript highlighting
- I also tried using a `tmTheme` file as well but still couldn't get the same result as the vim theme, the vim theme uses specific vim syntax highlighting which links us to the issue above

So, in the end, I just tried to use the original vim theme as an aspirational reference, with the strict rule was to use only colours in the original palette.

Perhaps we could start with some improvement suggestions for your programming languages, then we'll try and see how we would introduce the changes? PRs are welcomed too 👍

My thought is that if the changes aren't that much different from the current theme, we could introduce them to the existing theme. But if the changes would make everything rendered differently, then perhaps another variant as suggested, or a fork of this theme & published under another extension (I'm happy for people to fork this project, modify & publish if they want).

**Comment by prokolyvakis** [comment]
Hello, thank you a lot for your reply. First of all, I have to apologize for the vague "closer to the colour scheme". Using the theme the last month, I have to admit that the colour scheme is amazingly close to the gruvbox and the user experience in VS code is amazing. So thank you for your hard work! :)

The major difference that I managed to notice is only the background colour which is basically, at least to my eyes closer to grey. I would love to help, but I have to admit that my knowledge of on this regard is rather restricted. If you want I can also upload an image of how vim looks on my computer to better illustrate the differences and get your feedback.

Thank you very much for your reply and your amazing work once again!

**Comment by jdinhify** [comment]
Hey @prokolyvakis ,
Apologies for the late reply 🙏

I have checked with vim and can confirm that the background colour in vim by default isn't displayed exactly as the colour specified by gruvbox. The reason is that vim seems to use terminal colours by default, and displaying colours slightly different from the colours provided by the theme.

When using vim with terminals like iTerm or Hyper, I had the gui color turned on, which actually makes vim display the correct background colour ("correct" as in I verified by using a colour checker to check against the values in provided palette from https://github.com/morhetz/gruvbox)

```
set background=dark
set termguicolors
colorscheme gruvbox
```

screenshots
<img width="1250" alt="with-termguicolors" src="https://user-images.githubusercontent.com/14046273/132096213-b84186ba-ef1f-4c11-b6c8-36d6fbd027eb.png">
<img width="1250" alt="without-termguicolors" src="https://user-images.githubusercontent.com/14046273/132096215-983b1d5f-d0e4-47c0-9199-413bb84af393.png">

I'm not sure if this is the issue that you're seeing?

**Comment by prokolyvakis** [comment]
Hello, I truly apologize for the late response but somehow I did not see the notification of your reply. This is exactly what I was referring to, but I was not able to understand which was the factor that led to different colours!

**Comment by jdinhify** [comment]
Thanks for confirming @prokolyvakis 

I think turning off vim's `guicolors` makes the palette becomes a totally different thing, thus we won't be making change to this theme as it's referring to the true colours specified in gruvbox's colour palette.
I'll close this issue for now, but let me know if you have further advices/thoughts.
