### ISSUE TITLE
Is that possible to use other colors instead of red for types?

### ISSUE THREAD

**Issue by sgon00** [jdinhify/vscode-theme-gruvbox#5]
Hi, first, thank you very much for your hard work. I really like vim's gruvbox color scheme. I just installed and tried gruvbox in vscode today. I found out it used red colors for type. In the original vim's gruvbox scheme, it's not using red color for types. I just don't like too many red colors, 

* you can see there are too many red colors in the following two screenshots:

![vscode-1](https://user-images.githubusercontent.com/1555508/32981314-f58ab7bc-ccaf-11e7-907f-032a711fceb2.png)

![vscode-2](https://user-images.githubusercontent.com/1555508/32981318-fabc7b6c-ccaf-11e7-9595-8ee039af6e67.png)

Is that possible to use other colors such as yellow or orange for __TYPES__ instead of red?

* The following screenshot is from vim's gruvbox scheme:

![gvim-gruvbox](https://user-images.githubusercontent.com/1555508/32981423-afde00ba-ccb0-11e7-91b0-ef264115bc30.png)

Thank you very much.

**Comment by sgon00** [comment]
I fall in love with vim's gruvbox scheme. I tried many different gruvbox themes in vscode and I always feel something are very different and can not tell why. After I posted the above question (suggestion), I just found another problem. I found out the vim's gruvbox's white color is NOT really white. But this vscode's theme is truely white:

![compare](https://user-images.githubusercontent.com/1555508/32981595-8c0615ea-ccb2-11e7-8be6-59e5e600557a.png)

I am not sure if you can see the difference between the two white colors. I don't know how to express this in English. 100% <a color> is always NOT beautiful. 100% white, 100% red etc... 

Thank you very much.

**Comment by jdinhify** [comment]
Thanks @sgon00 , would you mind letting me know which language are you using? Is that golang?
It'd be great if you could provide me an example of a complete file using that language (to showcase possible syntax highlighting), so that I can put into [code-examples](https://github.com/jdinhify/vscode-theme-gruvbox/tree/master/code-examples) for future contributor to preview.

After having the language & example, I can change the type for that specific language like you suggested.

For the foreground color, it's not actually 100% white, it's the `fg0` color in the [gruvbox dark palette](https://github.com/morhetz/gruvbox). But I agree, it should be the `fg1` instead, I'll make this change quickly.

**Comment by jdinhify** [comment]
The foreground color has now been changed, your vscode should be able to upgrade.

CC @3ximus so that you're aware of the foreground color change

**Comment by sgon00** [comment]
Dear @jdinhify, thank you very much for your time and quick help. Yeah, I am using `golang`. The file I am using is https://github.com/dgraph-io/badger/blob/master/transaction.go . (I just randomly picked that one. )

Btw, I am new to vscode. I tried to update the extension to the latest version to see the foreground color change, but failed with the normal way. There was no "update" button in the vscode UI. I tried to uninstall and re-install this extension, but it was still the old version. I am not sure why. so instead of the normal update process, I did:

```shell
$ cd ~/.vscode/extensions
$ rm -rf jdinhlife.gruvbox-1.1.0/
$ git clone https://github.com/jdinhify/vscode-theme-gruvbox
```
I am not sure if I could do this or not...
Thank you very much for your kind help.

**Comment by 3ximus** [comment]
@sgon00 if that didn't work you should clone elsewhere and move the cloned repo, overwriting the needed files

**Comment by jdinhify** [comment]
Thanks @3ximus .

@sgon00 hmmm, I don't feel like cloning the repo manually gonna work since you'll want the auto-upgrade ability instead of going to the cloned repo and manually pulling every time.
I'm not sure how to help you with that though, if you install the extension using vscode's UI (extensions tab), it should be upgraded automatically unless you turned it off. 
Maybe just do what you're doing, but up to the 2nd step (`rm -rf...`), then restart vscode and try installing the theme again.

Btw, this is what I'm having for golang:
<img width="772" alt="golang" src="https://user-images.githubusercontent.com/14046273/32987391-a5bae27c-cd3e-11e7-99d7-219faeb63aec.png">
Let me know if you think anything doesn't feel right.

**Comment by sgon00** [comment]
@3ximus, thanks a lot for the advice.

@jdinhify,  
(1) Regarding vscode ext management: vscode is not trying to reinstall the extension after I `rm -rf`. I never turned off the auo-update feature, actually I don't know how to since I am really new to vscode. :) I am running vscode 1.17.2-1 in archlinux and upgrading to 1.18.1-1 now. Hopefully the problem will be fixed in the new version. I have a slow network, so the upgrading is still in progress. 
(2) Thank you very much for the quick fix and your hard work. The colors in your screenshot look __perfect__ to me. I just don't like too many red. :) 
_(Btw, maybe it's just the screenshot image, everything look bold. if they are not bold, just ignore me. )_

__Thank you very much!__

**Comment by sgon00** [comment]
Update: after upgrading to vscode 1.18.1, extensions can be auto-updated to latest versions. so the problem is fixed now. Cheers.

**Comment by jdinhify** [comment]
@sgon00 new version published, your vscode should be able to update to the latest one, then you can enjoy the new highlighting.

Everything is not bold, maybe just because I'm using a big font size or maybe the antialiasing makes them look bold.

**Comment by sgon00** [comment]
@jdinhify , yeah, I updated to the latest version. It looks amazing! The best gruvbox theme in vscode. Thank you very much for the quick fix and kind help. Closing this issue.
